GET http://localhost:9080/jakarta-exercise/api/users/1
###

GET http://localhost:9080/jakarta-exercise/api/users/2
###

GET http://localhost:9080/jakarta-exercise/api/users/3
###

GET http://localhost:9080/jakarta-exercise/api/users/4
###

GET http://localhost:9080/jakarta-exercise/api/users/5
###

GET http://localhost:9080/jakarta-exercise/api/users/0
###

GET http://localhost:9080/jakarta-exercise/api/users
###

POST http://localhost:9080/jakarta-exercise/api/avatars/1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="1.png'

< ../../src/main/resources/1.png
--boundary--

###


